export PATH=$HOME/.pyenv/bin:$HOME/bin:/usr/local/bin:$PATH:$HOME/.bin
export ZSH=$HOME/.oh-my-zsh
export EDITOR='emacs'

export NVM_DIR="$HOME/.nvm"

export GOPATH=$HOME/Documents/Go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PIP_REQUIRE_VIRTUALENV=true
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$WORK_FOLDER
export PYTHONBREAKPOINT=ipdb.set_trace

export GPG_TTY=$(tty)

export WORK_FOLDER=./Work/
export PROJECT_HOME=$WORK_FOLDER
export WORKON_HOME=$HOME/.virtualenvs

export AWS_VAULT_BACKEND=file