export PATH=$HOME/.pyenv/bin:$HOME/bin:/usr/local/bin:$HOME/bin:$HOME/.bin:$PATH
export ZSH=$HOME/.oh-my-zsh
export EDITOR="emacs"

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"

export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PIP_REQUIRE_VIRTUALENV=true
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$WORK_FOLDER
export PYTHONBREAKPOINT=ipdb.set_trace
export PATH="$HOME/.poetry/bin:$PATH"

export GPG_TTY=$(tty)

export WORK=${HOME}/dev
export NOTES=${HOME}/org
export PROJECT_HOME=$WORK_FOLDER

export HSTR_CONFIG=hicolor       # get more colors
export HISTCONTROL=ignorespace   # leading space hides commands from history
export HISTFILESIZE=10000        # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"

export NU_HOME=${HOME}/dev/nu
export NUCLI_HOME=${NU_HOME}/nucli
export PATH=${NUCLI_HOME}:${PATH}

export PATH="$PATH:$HOME/.config/emacs/bin"

# To fix the error to open firefox links
export MOZ_DBUS_REMOTE=1

# pgcli
PGSERVICEFILE=$HOME/.pg_service.conf
