export PATH=$HOME/.pyenv/bin:$HOME/.bin:$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
export EDITOR='emacs'

##### GO
export GOPATH=$HOME/Documents/Go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

##### Python
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PIP_REQUIRE_VIRTUALENV=true
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$WORK_FOLDER
export PYTHONBREAKPOINT=ipdb.set_trace

##### GPG Key
export GPG_TTY=$(tty)

##### Path configurations
export WORK_FOLDER=./Work/
export PROJECT_HOME=$WORK_FOLDER
export WORKON_HOME=$HOME/.virtualenvs
